version: '3.7'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
#            - "443:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
            - NGINX_ROOT=${NGINX_ROOT}
        command: /bin/sh -c "envsubst '$$NGINX_HOST $$NGINX_ROOT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        depends_on:
            - php
            - mysqldb
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./nginx/default.template:/etc/nginx/conf.d/default.template"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
#            - "./nginx/ssl:/etc/ssl"
            - "${APP_DIR}:/var/www/html:cached"
        restart: always
    php:
        build: ./php
        container_name: php
        ports:
            - "9000:9001"
        volumes:
            - "${APP_DIR}:/var/www/html:cached"
        working_dir: /var/www/html
        restart: always
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - "../data/db/mysql/:/var/lib/mysql"
        restart: always
    composer:
        image: composer
        container_name: composer
        volumes:
            - "${APP_DIR}:/app:cached"
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
            
volumes:
    php:
    nginx: